[profile.default]
extra_output = ["storageLayout"]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200

remappings = [
    "forge-std=lib/forge-std/src",
    "openzeppelin-contracts=lib/openzeppelin-contracts/contracts"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
